// <auto-generated />
using System;
using ImageLibrary.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageLibrary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903125749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImageLibrary.Server.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c9a3b0f-845a-4176-98ab-eca9073f5f96"),
                            CreatedAt = new DateTime(2026, 9, 3, 12, 57, 48, 60, DateTimeKind.Utc).AddTicks(8636),
                            Description = "Picture of Cat",
                            Name = "CuteCat",
                            UpdatedAt = new DateTime(2026, 9, 3, 12, 57, 48, 60, DateTimeKind.Utc).AddTicks(9093)
                        },
                        new
                        {
                            Id = new Guid("ee39641a-9c50-4055-b757-721a2db9e236"),
                            CreatedAt = new DateTime(2026, 9, 3, 12, 57, 48, 61, DateTimeKind.Utc).AddTicks(173),
                            Description = "Picture of Dog",
                            Name = "Doggy",
                            UpdatedAt = new DateTime(2026, 9, 3, 12, 57, 48, 61, DateTimeKind.Utc).AddTicks(174)
                        });
                });

            modelBuilder.Entity("ImageLibrary.Server.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ImageLibrary.Server.Domain.Entities.Tag", b =>
                {
                    b.HasOne("ImageLibrary.Server.Domain.Entities.Image", null)
                        .WithMany("Tags")
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("ImageLibrary.Server.Domain.Entities.Image", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
